FROM python:3
WORKDIR /code
ENV FLASK_RUN_HOST=0.0.0.0
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
#RUN pip install Flask-SQLAlchemy
EXPOSE 5000
COPY . .
CMD ["flask", "run"]
#CMD python src/market.py